### PR TITLE
Curveshot

### PR DESCRIPTION
**Pull request by CarpeSwag**
:construction: WIP Curveshot :construction:

I redid a bunch of things dealing with actually kicking the ball, then began Curveshot. As of right now, both curveshots only kick the ball and play a sound. At the moment, upon ball retrieval, the retrieving player regains 50 mana if they are a teammate of the player. I am going to make it so that you do not regain mana from self-passing because that just encourages selfish, wall-clinging gameplay.

Additionally, I'm going to give Storm Spirit his Ball Lightning as a sprint. It'll literally just be powersprint with a different aesthetic. The major difference will be that the sprint ends if you gain the ball. When you are carrying the ball, your sprint will revert back to the generic sprint so that you're not completely gimped (as is the case with powersprint to an extent). I will also be removing powersprint from the game and replacing it with a "powerdash" :D.

P.S. We don't actually have to enable curveshot on the release of Banjoball, but, fkyah, we gotta enable curveshot on the release of Banjoball.

Edit 1:
Curveshot basically looks like:
http://gfycat.com/DefensiveHarmoniousKillerwhale
except with a larger trail at the end.
P.S. That's Storm Spirit's hat particle as a trail.

P.P.S. So much spaghetti, so little code.

Edit 2:
Storm Spirit is almost complete:
http://gfycat.com/ClosedPastJaeger
http://gfycat.com/PoshGrimInsect
All I need to do is do some mana reworks in the code (both to make Arhowk happy ;) and to make ball lightning not go as far) and then I plan on reworking Invoker to remove his Powersprint.

Edit 3:
That was a lot easier than I thought it'd be. I just changed one constant basically to make it every .03 seconds.

### CODE REVIEW

**Comment by Arhowk** [comment]
Will the ball be untouchable during ball lightning?

**Comment by CarpeSwag** [comment]
It's literally going to be powersprint.

**Comment by Arhowk** [comment]
Would be way better if it was literally ball lightning.

**Comment by CarpeSwag** [comment]
What do you mean literally ball lightning O_O.

Animation-wise it will, and what you said is basically how powersprint functions.

**Comment by Arhowk** [comment]
Powersprint doesn't lock the ball out and can't travel through units, no?

also, powersprint has a sliding effect. Ball lightning should travel at a
constant velocity.

**Comment by CarpeSwag** [comment]
Powersprint travels at a constant velocity, and you already can't powersprint with the ball (you have to self-pass or steal the ball to be powersprinting with the ball).

**Comment by Arhowk** [comment]
oh, whatever. would be cooler if you could ball lightning w/ the ball

**Comment by CarpeSwag** [comment]
Yeah but that might be op. I'm leaving it as a potential buff, but IMO curveshot will get a lot of the things he needs from just having this sprint

**Comment by Arhowk** [comment]
do you remember what unpickable trash he was in banjoball? i mean he was
total absolute trash. I honestly don't think that the sprint buff will be
enough.

In addition, I have a further idea. I could add a particle indicating the
path that the ball will follow when you kick it.

This much is a pretty huge buff in terms of new players learning how to use
him and veterans knowing what the heck they're doing.

I have no problem with curveshot being a new god character :D its a cool
design.

**Comment by Arhowk** [comment]
on a side note, i won't be able to make the particle indicate collision
(unless i REALLY tried)

**Comment by CarpeSwag** [comment]
The lack of collision is fine. Would be pretty swaggy having any indicator.

Also, yes, I remember how much curveshot sucked. There's many reasons, but the biggest is that he only has offensive utility. His passing utility will be buffed via the mana gain and his defensive utility is MASSIVELY buffed with powersprint. Powersprint is great on defense and even gave Invoker goalie potential (admittedly not more than a real goalie, but still a good amount of potential). I'm not saying he will be OP, but I honestly believe he'll be semi-viable which is enough for now.

**Comment by Arhowk** [comment]
Being able to trace the ball exactly to make good passes would also be
quite helpful on defense :p

**Comment by Arhowk** [comment]
If you make the hero and whatnot so I can derive his physics I can make the
line indicator out of that

**Comment by Arhowk** [comment]
But we need physics engine first.

in the meantime, you should also make a 12x12 map :D

**Comment by CarpeSwag** [comment]
Yeah. When Garf redoes physics so much of the code will need to be revisited, but worth.

**Comment by CarpeSwag** [comment]
;) I'll fix it LOL

**Comment by CarpeSwag** [comment]
Curveshot and Powershot are done. I think the Invoker change might not be as useful as I hoped

**Pull request merged**
